dist: trusty
sudo: false
addons:
  apt:
    packages:
      - google-chrome-stable
language:
  - node_js
nvm:
  - 6.10.1
git:
  depth: 1
cache:
  yarn: true
  directories: node_modules
script:
  - yarn test
after_success:
  - cat ./.tmp/coverage/report/lcov.info | ./node_modules/.bin/coveralls
