dist: trusty
sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language:
  - node_js
node_js:
  - stable
git:
  depth: 1
cache:
  yarn: true
  directories: node_modules
script:
  - yarn test
after_success:
  - cat ./app/coverage/report/lcov.info | ./node_modules/.bin/coveralls
