dist: trusty
sudo: false
language:
  - node_js
node_js:
  - stable
git:
  depth: 1
cache:
  yarn: true
  directories: node_modules
before_install:
  - export CHROME_BIN=google-chrome-stable
script:
  - yarn test
after_success:
  - cat ./app/coverage/report/lcov.info | ./node_modules/.bin/coveralls
